plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.javalin:javalin:6.7.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
}

sourceSets {
    main {
        resources {
            srcDir 'src/main/java'
            include '**/*.json'
        }
    }
}

application {
    mainClass = 'com.api.App'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}